- name: Cleanup k3s installation on master
  hosts: master
  gather_facts: false
  tasks:
    - name: Run k3s uninstall script
      shell: /usr/local/bin/k3s-uninstall.sh
    - name: Remove k3s directory
      shell: rm -rf /var/lib/rancher
- name: Cleanup k3s installation on workers
  hosts: workers
  gather_facts: false
  tasks:
    - name: Run k3s uninstall script
      shell: /usr/local/bin/k3s-agent-uninstall.sh
    - name: Remove k3s directory
      shell: rm -rf /var/lib/rancher